package cn.xgs.domain.dto;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.fasterxml.jackson.annotation.JsonInclude;
import lombok.Data;

import java.util.*;
@Data
public class SysMenu {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.menu_id
     *
     * @mbg.generated Wed Sep 18 22:51:36 CST 2024
     */
    @TableId(value = "menu_id",type = IdType.AUTO)
    private Long menuId;
    /**
     * 菜单图标
     */
    private String icon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.menu_name
     *
     * @mbg.generated Wed Sep 18 22:51:36 CST 2024
     */
    private String menuName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.parent_name
     *
     * @mbg.generated Wed Sep 18 22:51:36 CST 2024
     */
    private String parentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.parent_id
     *
     * @mbg.generated Wed Sep 18 22:51:36 CST 2024
     */
    private Long parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.order_num
     *
     * @mbg.generated Wed Sep 18 22:51:36 CST 2024
     */
    private Integer orderNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.path
     *
     * @mbg.generated Wed Sep 18 22:51:36 CST 2024
     */
    private String path;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.component
     *
     * @mbg.generated Wed Sep 18 22:51:36 CST 2024
     */
    private String component;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.chain
     *
     * @mbg.generated Wed Sep 18 22:51:36 CST 2024
     */
    private String chain;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.query
     *
     * @mbg.generated Wed Sep 18 22:51:36 CST 2024
     */
    private String query;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.is_frame
     *
     * @mbg.generated Wed Sep 18 22:51:36 CST 2024
     */
    private String isFrame;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.is_cache
     *
     * @mbg.generated Wed Sep 18 22:51:36 CST 2024
     */
    private String isCache;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.menu_type
     *
     * @mbg.generated Wed Sep 18 22:51:36 CST 2024
     */
    private String menuType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.visible
     *
     * @mbg.generated Wed Sep 18 22:51:36 CST 2024
     */
    private String visible;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.catalog_status
     *
     * @mbg.generated Wed Sep 18 22:51:36 CST 2024
     */
    private String catalogStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.perms
     *
     * @mbg.generated Wed Sep 18 22:51:36 CST 2024
     */
    private String perms;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.create_by
     *
     * @mbg.generated Wed Sep 18 22:51:36 CST 2024
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.create_time
     *
     * @mbg.generated Wed Sep 18 22:51:36 CST 2024
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.update_by
     *
     * @mbg.generated Wed Sep 18 22:51:36 CST 2024
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.update_time
     *
     * @mbg.generated Wed Sep 18 22:51:36 CST 2024
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.remark
     *
     * @mbg.generated Wed Sep 18 22:51:36 CST 2024
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.menu_id
     *
     * @return the value of sys_menu.menu_id
     *
     * @mbg.generated Wed Sep 18 22:51:36 CST 2024
     */
    public Long getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.menu_id
     *
     * @param menuId the value for sys_menu.menu_id
     *
     * @mbg.generated Wed Sep 18 22:51:36 CST 2024
     */
    public void setMenuId(Long menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.menu_name
     *
     * @return the value of sys_menu.menu_name
     *
     * @mbg.generated Wed Sep 18 22:51:36 CST 2024
     */
    public String getMenuName() {
        return menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.menu_name
     *
     * @param menuName the value for sys_menu.menu_name
     *
     * @mbg.generated Wed Sep 18 22:51:36 CST 2024
     */
    public void setMenuName(String menuName) {
        this.menuName = menuName == null ? null : menuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.parent_name
     *
     * @return the value of sys_menu.parent_name
     *
     * @mbg.generated Wed Sep 18 22:51:36 CST 2024
     */
    public String getParentName() {
        return parentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.parent_name
     *
     * @param parentName the value for sys_menu.parent_name
     *
     * @mbg.generated Wed Sep 18 22:51:36 CST 2024
     */
    public void setParentName(String parentName) {
        this.parentName = parentName == null ? null : parentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.parent_id
     *
     * @return the value of sys_menu.parent_id
     *
     * @mbg.generated Wed Sep 18 22:51:36 CST 2024
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.parent_id
     *
     * @param parentId the value for sys_menu.parent_id
     *
     * @mbg.generated Wed Sep 18 22:51:36 CST 2024
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.order_num
     *
     * @return the value of sys_menu.order_num
     *
     * @mbg.generated Wed Sep 18 22:51:36 CST 2024
     */
    public Integer getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.order_num
     *
     * @param orderNum the value for sys_menu.order_num
     *
     * @mbg.generated Wed Sep 18 22:51:36 CST 2024
     */
    public void setOrderNum(Integer orderNum) {
        this.orderNum = orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.path
     *
     * @return the value of sys_menu.path
     *
     * @mbg.generated Wed Sep 18 22:51:36 CST 2024
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.path
     *
     * @param path the value for sys_menu.path
     *
     * @mbg.generated Wed Sep 18 22:51:36 CST 2024
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.component
     *
     * @return the value of sys_menu.component
     *
     * @mbg.generated Wed Sep 18 22:51:36 CST 2024
     */
    public String getComponent() {
        return component;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.component
     *
     * @param component the value for sys_menu.component
     *
     * @mbg.generated Wed Sep 18 22:51:36 CST 2024
     */
    public void setComponent(String component) {
        this.component = component == null ? null : component.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.chain
     *
     * @return the value of sys_menu.chain
     *
     * @mbg.generated Wed Sep 18 22:51:36 CST 2024
     */
    public String getChain() {
        return chain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.chain
     *
     * @param chain the value for sys_menu.chain
     *
     * @mbg.generated Wed Sep 18 22:51:36 CST 2024
     */
    public void setChain(String chain) {
        this.chain = chain == null ? null : chain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.query
     *
     * @return the value of sys_menu.query
     *
     * @mbg.generated Wed Sep 18 22:51:36 CST 2024
     */
    public String getQuery() {
        return query;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.query
     *
     * @param query the value for sys_menu.query
     *
     * @mbg.generated Wed Sep 18 22:51:36 CST 2024
     */
    public void setQuery(String query) {
        this.query = query == null ? null : query.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.is_frame
     *
     * @return the value of sys_menu.is_frame
     *
     * @mbg.generated Wed Sep 18 22:51:36 CST 2024
     */
    public String getIsFrame() {
        return isFrame;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.is_frame
     *
     * @param isFrame the value for sys_menu.is_frame
     *
     * @mbg.generated Wed Sep 18 22:51:36 CST 2024
     */
    public void setIsFrame(String isFrame) {
        this.isFrame = isFrame == null ? null : isFrame.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.is_cache
     *
     * @return the value of sys_menu.is_cache
     *
     * @mbg.generated Wed Sep 18 22:51:36 CST 2024
     */
    public String getIsCache() {
        return isCache;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.is_cache
     *
     * @param isCache the value for sys_menu.is_cache
     *
     * @mbg.generated Wed Sep 18 22:51:36 CST 2024
     */
    public void setIsCache(String isCache) {
        this.isCache = isCache == null ? null : isCache.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.menu_type
     *
     * @return the value of sys_menu.menu_type
     *
     * @mbg.generated Wed Sep 18 22:51:36 CST 2024
     */
    public String getMenuType() {
        return menuType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.menu_type
     *
     * @param menuType the value for sys_menu.menu_type
     *
     * @mbg.generated Wed Sep 18 22:51:36 CST 2024
     */
    public void setMenuType(String menuType) {
        this.menuType = menuType == null ? null : menuType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.visible
     *
     * @return the value of sys_menu.visible
     *
     * @mbg.generated Wed Sep 18 22:51:36 CST 2024
     */
    public String getVisible() {
        return visible;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.visible
     *
     * @param visible the value for sys_menu.visible
     *
     * @mbg.generated Wed Sep 18 22:51:36 CST 2024
     */
    public void setVisible(String visible) {
        this.visible = visible == null ? null : visible.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.catalog_status
     *
     * @return the value of sys_menu.catalog_status
     *
     * @mbg.generated Wed Sep 18 22:51:36 CST 2024
     */
    public String getCatalogStatus() {
        return catalogStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.catalog_status
     *
     * @param catalogStatus the value for sys_menu.catalog_status
     *
     * @mbg.generated Wed Sep 18 22:51:36 CST 2024
     */
    public void setCatalogStatus(String catalogStatus) {
        this.catalogStatus = catalogStatus == null ? null : catalogStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.perms
     *
     * @return the value of sys_menu.perms
     *
     * @mbg.generated Wed Sep 18 22:51:36 CST 2024
     */
    public String getPerms() {
        return perms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.perms
     *
     * @param perms the value for sys_menu.perms
     *
     * @mbg.generated Wed Sep 18 22:51:36 CST 2024
     */
    public void setPerms(String perms) {
        this.perms = perms == null ? null : perms.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.create_by
     *
     * @return the value of sys_menu.create_by
     *
     * @mbg.generated Wed Sep 18 22:51:36 CST 2024
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.create_by
     *
     * @param createBy the value for sys_menu.create_by
     *
     * @mbg.generated Wed Sep 18 22:51:36 CST 2024
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.create_time
     *
     * @return the value of sys_menu.create_time
     *
     * @mbg.generated Wed Sep 18 22:51:36 CST 2024
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.create_time
     *
     * @param createTime the value for sys_menu.create_time
     *
     * @mbg.generated Wed Sep 18 22:51:36 CST 2024
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.update_by
     *
     * @return the value of sys_menu.update_by
     *
     * @mbg.generated Wed Sep 18 22:51:36 CST 2024
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.update_by
     *
     * @param updateBy the value for sys_menu.update_by
     *
     * @mbg.generated Wed Sep 18 22:51:36 CST 2024
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.update_time
     *
     * @return the value of sys_menu.update_time
     *
     * @mbg.generated Wed Sep 18 22:51:36 CST 2024
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.update_time
     *
     * @param updateTime the value for sys_menu.update_time
     *
     * @mbg.generated Wed Sep 18 22:51:36 CST 2024
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.remark
     *
     * @return the value of sys_menu.remark
     *
     * @mbg.generated Wed Sep 18 22:51:36 CST 2024
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.remark
     *
     * @param remark the value for sys_menu.remark
     *
     * @mbg.generated Wed Sep 18 22:51:36 CST 2024
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
    /**
     * 子菜单
     */
    private List<SysMenu> children = new ArrayList<SysMenu>();

    /**
     * 请求参数
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Map<String, Object> params;

    public Map<String, Object> getParams() {
        if (params == null) {
            params = new HashMap<>();
        }
        return params;
    }

}